# Generated by Django 2.2.2 on 2023-09-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=15)),
                ('test_1', models.IntegerField()),
                ('midexam', models.IntegerField()),
                ('test_2', models.IntegerField()),
                ('Assignment', models.IntegerField()),
                ('final_exam', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
