# Generated by Django 2.2.2 on 2023-09-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_auto_20230910_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='name',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='name',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
