# Generated by Django 2.2.2 on 2023-09-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_auto_20230910_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='fullname',
        ),
    ]
