# Generated by Django 4.2.5 on 2023-10-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('phy', models.IntegerField()),
                ('english', models.IntegerField()),
                ('cvc', models.IntegerField()),
                ('hpe', models.IntegerField()),
                ('bio', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='takencourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='takencourse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='takencourse',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='TakenCourse',
        ),
    ]
