# Generated by Django 4.2.5 on 2023-09-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100, unique=True)),
                ('math', models.IntegerField(max_length=2, null=True)),
                ('english', models.IntegerField(max_length=2, null=True)),
                ('physics', models.IntegerField(max_length=2, null=True)),
                ('chemistry', models.IntegerField(max_length=2, null=True)),
                ('hpe', models.IntegerField(max_length=2, null=True)),
                ('it', models.IntegerField(max_length=2, null=True)),
            ],
        ),
    ]
