# Generated by Django 4.2.5 on 2023-09-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_grade_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade_table',
            name='chemistry',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade_table',
            name='english',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade_table',
            name='hpe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade_table',
            name='it',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade_table',
            name='math',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade_table',
            name='physics',
            field=models.IntegerField(null=True),
        ),
    ]
