# Generated by Django 4.2.5 on 2023-10-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_table_alter_takencourse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='bio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='cvc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='english',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='hpe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='phy',
            field=models.IntegerField(null=True),
        ),
    ]
