# Generated by Django 4.2.5 on 2023-10-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_alter_table_bio_alter_table_cvc_alter_table_english_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test1', models.IntegerField(null=True)),
                ('Test2', models.IntegerField(null=True)),
                ('MidExam', models.IntegerField(null=True)),
                ('Assignment', models.IntegerField(null=True)),
                ('FinalExam', models.IntegerField(null=True)),
                ('Total', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phy', models.IntegerField(null=True)),
                ('english', models.IntegerField(null=True)),
                ('cvc', models.IntegerField(null=True)),
                ('hpe', models.IntegerField(null=True)),
                ('bio', models.IntegerField(null=True)),
                ('studentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.studentname')),
            ],
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.AddField(
            model_name='grades',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.subjects'),
        ),
    ]
