# Generated by Django 4.2.5 on 2023-09-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_alter_grade_table_chemistry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade_Table',
        ),
    ]
