# Generated by Django 4.2.5 on 2023-10-06 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0015_delete_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_1', models.IntegerField(null=True)),
                ('test_2', models.IntegerField(null=True)),
                ('mid_exam', models.IntegerField(null=True)),
                ('assignment', models.IntegerField(null=True)),
                ('final_exam', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentname',
            new_name='student_name',
        ),
        migrations.RenameModel(
            old_name='StudentName',
            new_name='Student',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.subject'),
        ),
    ]
