# Generated by Django 4.2.4 on 2023-08-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Parents',
        ),
    ]
